In [ ]:
# @title
# Curso IA Aplicada aos Desafios Socioambientais da Amazônia
# Notebook desenvolvido por: Onédio S Seabra junior
# Atualização : 15 de setembro de 2025

from IPython.display import display, HTML

# O caminho para a imagem
header_img = 'https://i.postimg.cc/QxbdgYNJ/header-encontro18.png'
# O código HTML para exibir a imagem em tamanho original e centralizada
html = f'<img src="{header_img}" style="display: block; margin: 0 auto; width: 100%; height: 100%; object-fit: contain">'
# Exibe a imagem usando o display do IPython e o HTML
display(HTML(html))

# **&#9776; Metodologia CRISP-DM**
---

<h4 align="justify">É a metodologia mais usada em Data Science. Define um ciclo de vida com seis fases: entendimento do negócio, entendimento dos dados, preparação dos dados, modelagem, avaliação e implantação.</h4>
<br>
<center><img width="60%" src="https://i.postimg.cc/3wBmx1zb/crisp-dm.png"></center>

# **&#9776; Tipos de Algoritmos de Classificação**
<hr>

<h4 align="justify">Os algoritmos de classificação são fundamentais em aprendizado de máquina, pois permitem prever categorias ou rótulos a partir de dados históricos. Entre os tipos mais clássicos estão a Regressão Logística, usada em problemas binários e multiclasse; o Naive Bayes, baseado em probabilidades e útil em textos; e o k-Nearest Neighbors (k-NN), que classifica novos exemplos considerando a proximidade de vizinhos no espaço de atributos. Cada um possui particularidades que os tornam mais adequados a determinados contextos, como simplicidade, velocidade ou interpretabilidade.</h4>
<h4 align="justify">Além deles, destacam-se as Árvores de Decisão, de fácil visualização e interpretação, o Random Forest, que combina várias árvores para maior robustez, e as Máquinas de Vetores de Suporte (SVM), eficientes em dados complexos e de alta dimensionalidade. A escolha do algoritmo depende não apenas da natureza do problema e do tamanho do dataset, mas também da <b>necessidade de interpretabilidade, da precisão desejada e da capacidade computacional disponível.</b></h4>
<br/>

# **&#9776; Naive Bayes**
---

<h4 align="justify">O algoritmo de Naive Bayes é um classificador probabilístico baseado no Teorema de Bayes, que parte da suposição de independência entre as variáveis explicativas. Em termos práticos, ele calcula a probabilidade de uma determinada classe ocorrer dado um conjunto de atributos, escolhendo sempre a classe mais provável. Sua simplicidade o torna adequado para lidar com grandes volumes de dados heterogêneos, característica comum em contextos socioambientais, pois consegue processar rapidamente informações categóricas ou numéricas sem exigir muitos recursos computacionais.</h4>
<h4 align="justify">No contexto da Amazônia e da COP30, o Naive Bayes pode ser aplicado para classificar riscos socioambientais, prever categorias de impacto ambiental ou identificar padrões de vulnerabilidade em comunidades locais. Por exemplo, com base em dados sobre desmatamento, qualidade da água, uso da terra e variáveis climáticas, o algoritmo pode ajudar a prever áreas de maior risco de degradação ou indicar regiões prioritárias para ações de mitigação. Assim, ele funciona como um apoio estratégico à tomada de decisão, orientando políticas públicas e iniciativas sustentáveis durante e após o evento</h4>

# **:: O que é o Classificador Naive Bayes**

<h4 align="justify">O Naive Bayes é um algoritmo de classificação estatística fundamentado no Teorema de Bayes e amplamente utilizado em aprendizado supervisionado. Reconhecido por sua simplicidade, ele se destaca por ser um método rápido, preciso e confiável, especialmente quando <b>aplicado em grandes volumes de dados</b>. Sua eficiência computacional o torna bastante útil em cenários que exigem <b>respostas ágeis e análises em tempo real.</b></h4>
<hr/>
<br/>

$$
P(h \mid D) = \frac{P(D \mid h) \cdot P(h)}{P(D)}
$$

**Definições:**

- **P(h):** a probabilidade de a hipótese *h* ser verdadeira (independentemente dos dados).  
  → Conhecida como **probabilidade prévia** de *h*.  

- **P(D):** a probabilidade dos dados (independentemente da hipótese).  
  → Conhecida como **probabilidade prévia** dos dados.  

- **P(h|D):** a probabilidade da hipótese *h* com base nos dados *D*.  
  → Conhecida como **probabilidade posterior**.  

- **P(D|h):** a probabilidade dos dados *D*, se a hipótese *h* for verdadeira.  
  → Conhecida como **verossimilhança**.

# **:: Como funciona o Classificador Naive Bayes**

<h4 align="justify">Vamos entender o funcionamento do Naive Bayes por meio de um exemplo. Imagine que estamos analisando comunidades ribeirinhas na Amazônia para identificar se uma determinada região está em “risco socioambiental alto” ou “risco socioambiental baixo”. As variáveis consideradas são: qualidade da água (boa ou ruim), nível de desmatamento (baixo ou alto) e ocorrência de queimadas (sim ou não). Cada uma dessas características é tratada como independente pelo algoritmo, mesmo que na realidade possam estar correlacionadas.</h4>
<h4 align="justify">Com base em dados históricos, o Naive Bayes calcula a probabilidade de uma nova comunidade pertencer a cada classe (alto ou baixo risco), dado o conjunto de atributos observados. Assim, se uma região apresenta água de baixa qualidade, alto desmatamento e ocorrência de queimadas, o algoritmo combina essas probabilidades e classifica a área como “alto risco socioambiental”. Esse processo, apesar de simples, permite apoiar decisões rápidas e fundamentadas, sendo útil em contextos como a COP30, onde há necessidade de identificar áreas críticas para priorizar políticas de proteção e mitigação ambiental.</h4>

| ID | Água | Desmat. | Queimada | Risco |
| -: | :--: | :-----: | :------: | :---: |
|  1 | Ruim |   Alto  |    Sim   |  Alto |
|  2 | Ruim |   Alto  |    Não   |  Alto |
|  3 |  Boa |   Alto  |    Sim   |  Alto |
|  4 | Ruim |  Baixo  |    Sim   |  Alto |
|  5 |  Boa |  Baixo  |    Sim   |  Alto |
|  6 |  Boa |   Alto  |    Não   |  Alto |
|  7 |  Boa |  Baixo  |    Não   | Baixo |
|  8 |  Boa |  Baixo  |    Sim   | Baixo |
|  9 |  Boa |   Alto  |    Não   | Baixo |
| 10 | Ruim |  Baixo  |    Não   | Baixo |

### Frequências por classe (priors):
$$ P(\text{Alto}) = 6/10 = 0,6 \; ; \; P(\text{Baixo}) = 4/10 = 0,4 $$

### Likelihoods (por classe):

- Para **Alto**:  
  $$ P(\text{Água=Ruim} \mid \text{Alto}) = 3/6 = 0,5 $$
  
  $$ P(\text{Desmat=Alto} \mid \text{Alto}) = 4/6 \approx 0,667 $$  
  
  $$ P(\text{Queimada=Sim} \mid \text{Alto}) = 4/6 \approx 0,667 $$  

- Para **Baixo**:  
  $$ P(\text{Água=Ruim} \mid \text{Baixo}) = 1/4 = 0,25 $$
  
  $$ P(\text{Desmat=Alto} \mid \text{Baixo}) = 1/4 = 0,25 $$

  $$ P(\text{Queimada=Sim} \mid \text{Baixo}) = 1/4 = 0,25 $$

# **:: Vídeo de Apoio para o Classificador Naive Bayes**

https://www.youtube.com/watch?v=Bk2mSIMw_XE

# **:: Exemplo do uso do Classificador Naive Bayes**

<h4 align="justify">Em uma região amazônica, gestores ambientais querem prever se uma comunidade ribeirinha está em alto ou baixo risco socioambiental. Para isso, utilizam dados sobre a qualidade da água, o nível de desmatamento e a ocorrência de queimadas. Esses fatores, embora relacionados entre si, são tratados de forma independente pelo classificador Naive Bayes, simplificando o processo de análise.</h4>
<h4 align="justify">O objetivo é treinar um modelo que, a partir de exemplos históricos, consiga classificar novas comunidades. Para isso, é fornecido um conjunto de dados fictício com 100 instâncias, onde cada linha corresponde a uma situação registrada, incluindo variáveis ambientais e o rótulo de risco socioambiental associado.</h4>
<h4 align="justify">Você deve aplicar o algoritmo de Naive Bayes nesse conjunto de dados para aprender as relações probabilísticas entre os atributos e o risco. Em seguida, poderá testar a classificação de novas instâncias e verificar se o modelo consegue identificar corretamente áreas de alto risco e de baixo risco.</h4>

In [ ]:
#carregar biblioteca
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# carregar o dataset
df = pd.read_csv("/content/dataset_naive_bayes_socioambiental.csv")

df.sample(3)

    Agua Desmatamento Queimada  Risco
79  Ruim        Baixo      Sim   Alto
3    Boa        Baixo      Sim  Baixo
60  Ruim         Alto      Sim   Alto

In [ ]:
# separar features e classe
X = df[['Agua', 'Desmatamento', 'Queimada']]
y = df['Risco']  # classes: "Alto" ou "Baixo"

In [ ]:
# separar dados de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [ ]:
# Pipeline: codificação categórica + Naive Bayes
# CategoricalNB requer inteiros para categorias -> usamos OrdinalEncoder
cat_features = ['Agua', 'Desmatamento', 'Queimada']
preprocess = ColumnTransformer(
    transformers=[('cat', OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1), cat_features)],
    remainder='drop' #passthrough
)

model = Pipeline(steps=[
    ("prep", preprocess),
    ("nb", CategoricalNB())
])

# === 6) Treinar ===
model.fit(X_train, y_train)

# === 7) Avaliar ===
y_pred = model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
cm  = confusion_matrix(y_test, y_pred, labels=["Alto","Baixo"])

print(f"Acurácia no teste: {acc:.3f}")
print("\nMatriz de confusão (linhas=verdadeiro, colunas=previsto) [ordem: Alto, Baixo]:")
print(cm)
print("\nRelatório de classificação:")
print(classification_report(y_test, y_pred, digits=3))

Acurácia no teste: 0.767

Matriz de confusão (linhas=verdadeiro, colunas=previsto) [ordem: Alto, Baixo]:
[[ 9  4]
 [ 3 14]]

Relatório de classificação:
              precision    recall  f1-score   support

        Alto      0.750     0.692     0.720        13
       Baixo      0.778     0.824     0.800        17

    accuracy                          0.767        30
   macro avg      0.764     0.758     0.760        30
weighted avg      0.766     0.767     0.765        30

In [ ]:
# exemplo de previsão
exemplo = pd.DataFrame([{"Agua": "Ruim", "Desmatamento": "Alto", "Queimada": "Sim"}])
proba = model.predict_proba(exemplo)[0]
pred = model.predict(exemplo)[0]

print("\nExemplo de entrada:", dict(exemplo.iloc[0]))
print("Probabilidades (ordem de classes):", model.classes_)
print([round(p, 4) for p in proba])
print("Classe prevista:", pred)

Exemplo de entrada: {'Agua': 'Ruim', 'Desmatamento': 'Alto', 'Queimada': 'Sim'}
Probabilidades (ordem de classes): ['Alto' 'Baixo']
[np.float64(0.7386), np.float64(0.2614)]
Classe prevista: Alto

# **&#9776; KNN**
---

<h4 align="justify">O algoritmo KNN (K-Nearest Neighbors) é um classificador baseado na proximidade entre instâncias em um espaço de atributos. Em termos práticos, ele armazena os dados de treinamento e, quando precisa classificar uma nova amostra, calcula a distância dela em relação a todas as demais, selecionando os K vizinhos mais próximos. A classe mais frequente entre esses vizinhos é atribuída à nova instância. Sua simplicidade conceitual o torna intuitivo e eficaz em diferentes domínios, especialmente em cenários em que a similaridade entre observações é um fator relevante.</h4>
<h4 align="justify">No contexto da Amazônia e da COP30, o KNN pode ser aplicado para identificar áreas ou comunidades com perfis socioambientais semelhantes. Por exemplo, considerando variáveis como nível de desmatamento, qualidade da água, incidência de queimadas e densidade populacional, o algoritmo pode classificar uma nova região como de alto ou baixo risco socioambiental com base em regiões vizinhas que compartilham características parecidas. Assim, o KNN auxilia na detecção de padrões locais de risco, oferecendo suporte à tomada de decisões em políticas públicas, estratégias de mitigação e ações de preservação ambiental.</h4>

# **:: Como funciona o KNN**
---

<h4 align="justify">Vamos entender o funcionamento do KNN (K-Nearest Neighbors) por meio de um exemplo. Imagine que estamos analisando comunidades ribeirinhas na Amazônia para identificar se uma determinada região está em “risco socioambiental alto” ou “risco socioambiental baixo”. As variáveis consideradas são: qualidade da água, nível de desmatamento e ocorrência de queimadas. Diferente do Naive Bayes, o KNN não parte de probabilidades, mas sim da distância entre os dados: quanto mais próximas duas regiões estiverem em termos de atributos, mais semelhantes elas são consideradas.</h4>
<h4 align="justify">Com base em dados históricos já classificados, o KNN avalia uma nova comunidade calculando sua distância em relação a todas as demais e seleciona os K vizinhos mais próximos. A classe é então atribuída de acordo com a maioria desses vizinhos. Assim, se a maioria das comunidades mais próximas está em “alto risco socioambiental”, a nova comunidade também será classificada dessa forma. Esse processo intuitivo permite que o KNN identifique padrões locais e apoie decisões sobre áreas críticas, algo especialmente útil no contexto da COP30, em que há necessidade de orientar políticas públicas e ações de mitigação em regiões com características ambientais semelhantes.</h4>

<center><img src="https://i.postimg.cc/SQvfK5GP/Chat-GPT-Image-16-de-set-de-2025-21-36-17.png"></center>

# **:: Exemplo do uso do Classificador KNN**
---

In [ ]:
# carrega bibliotecas
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [ ]:
# carregar o dataset
df = pd.read_csv("/content/dataset_naive_bayes_socioambiental.csv")

df.sample(3)

   Agua Desmatamento Queimada  Risco
25  Boa        Baixo      Sim  Baixo
63  Boa         Alto      Sim  Baixo
80  Boa        Baixo      Não  Baixo

In [ ]:
# separar dados de treino e teste
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)

In [ ]:
# Pipeline: OneHotEncoder + KNN
preprocess = ColumnTransformer([
    ('cat', OneHotEncoder(handle_unknown='ignore'),
     ['Agua', 'Desmatamento', 'Queimada'])
])

pipe = Pipeline([
    ('prep', preprocess),
    ('knn', KNeighborsClassifier())
])

In [ ]:
# Busca de hiperparâmetros no conjunto de treino (CV)
param_grid = {
    'knn__n_neighbors': [3, 5, 7, 9],
    'knn__weights': ['uniform', 'distance'],
    'knn__metric': ['minkowski', 'manhattan']
}
grid = GridSearchCV(pipe, param_grid, scoring='accuracy', cv=5, refit=True)
grid.fit(X_train, y_train)
best_model = grid.best_estimator_

In [ ]:
# Avaliação no conjunto de TESTE
y_pred = best_model.predict(X_test)
acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred, labels=['Alto', 'Baixo'])
print("Melhores hiperparâmetros:", grid.best_params_)
print(f"Acurácia no TESTE: {acc:.3f}")
print("Matriz de confusão (linhas=verdadeiro, colunas=previsto) [Alto, Baixo]:\n", cm)
print("\nRelatório de classificação:\n", classification_report(y_test, y_pred, digits=3))

Melhores hiperparâmetros: {'knn__metric': 'minkowski', 'knn__n_neighbors': 7, 'knn__weights': 'uniform'}
Acurácia no TESTE: 0.767
Matriz de confusão (linhas=verdadeiro, colunas=previsto) [Alto, Baixo]:
 [[ 9  4]
 [ 3 14]]

Relatório de classificação:
               precision    recall  f1-score   support

        Alto      0.750     0.692     0.720        13
       Baixo      0.778     0.824     0.800        17

    accuracy                          0.767        30
   macro avg      0.764     0.758     0.760        30
weighted avg      0.766     0.767     0.765        30

In [ ]:
# Exemplo de predição
exemplo = pd.DataFrame([{"Agua": "Ruim", "Desmatamento": "Alto", "Queimada": "Sim"}])
pred = best_model.predict(exemplo)[0]
proba = best_model.predict_proba(exemplo)[0]
print("Exemplo:", exemplo.iloc[0].to_dict())
print("Ordem das classes:", list(best_model.named_steps['knn'].classes_))
print("Probabilidades:", [round(p, 4) for p in proba])
print("Classe prevista:", pred)

Exemplo: {'Agua': 'Ruim', 'Desmatamento': 'Alto', 'Queimada': 'Sim'}
Ordem das classes: ['Alto', 'Baixo']
Probabilidades: [np.float64(0.8571), np.float64(0.1429)]
Classe prevista: Alto

# **&#9776; SVM**
---

<h4 align="justify">O algoritmo SVM (Support Vector Machine) é um classificador que busca encontrar o hiperplano ótimo que melhor separa as classes em um espaço de atributos. Em termos práticos, ele identifica a fronteira de decisão que maximiza a margem entre os exemplos de classes diferentes, ou seja, a distância entre os pontos mais próximos de cada classe e o hiperplano. Essa característica faz com que o SVM seja robusto e eficiente, especialmente em problemas com alta dimensionalidade e em cenários onde é importante ter uma clara separação entre categorias.</h4>
<h4 align="justify">No contexto da Amazônia e da COP30, o SVM pode ser aplicado para distinguir regiões ou comunidades em diferentes níveis de risco socioambiental. Por exemplo, utilizando variáveis como qualidade da água, extensão do desmatamento, ocorrência de queimadas e indicadores sociais, o algoritmo pode aprender a fronteira que separa áreas de alto risco e baixo risco. Dessa forma, o SVM ajuda a identificar limites críticos de vulnerabilidade ambiental e social, permitindo direcionar ações estratégicas de prevenção e políticas públicas de forma mais assertiva, apoiando o planejamento sustentável da região.</h4>

# **:: Tipos de Algoritmos**
---

<h4 align="justify"><b>SVM Linear:</b> Somente quando os dados são perfeitamente separáveis ​​linearmente é que podemos usar o SVM Linear. Perfeitamente separável linearmente significa que os pontos de dados podem ser classificados em duas classes usando uma única linha reta (se 2D).</h4>
<h4 align="justify"><b>SVM Não Linear:</b> Quando os dados não são linearmente separáveis, podemos usar SVM Não Linear. Isso acontece quando os pontos de dados não podem ser separados em duas classes usando uma linha reta (se 2D). Nesses casos, usamos técnicas avançadas, como truques de kernel, para classificá-los. Na maioria das aplicações do mundo real, não encontramos pontos de dados linearmente separáveis, portanto, usamos truques de kernel para resolvê-los.</h4>

# **:: Como funciona o SVM**
---

<h4 align="justify">Vamos entender o funcionamento do SVM (Support Vector Machine) por meio de um exemplo.  Suponha que temos um conjunto de dados com duas classes (verde e azul). Queremos classificar o novo ponto de dados como azul ou verde.</h4>

<center><img src="https://i.postimg.cc/tJgK8y5j/467902-1.webp"></center>

<h4 align="justify">Para classificar esses pontos, podemos ter muitos limites de decisão, mas a questão é qual é o melhor e como encontrá-lo?</h4>
<h4 align="justify"><b>NOTA:</b> Como estamos plotando os pontos de dados em um gráfico bidimensional, chamamos esse limite de decisão de linha reta, mas se tivermos mais dimensões, chamamos esse limite de decisão de “hiperplano”.</h4>

<center><img src="https://i.postimg.cc/zfqYT4QT/492453.webp"></center>

<h4 align="justify">O melhor hiperplano é aquele que possui a distância máxima de ambas as classes, e este é o principal objetivo do SVM. Isso é feito encontrando diferentes hiperplanos que classificam os rótulos da melhor maneira possível, e então ele escolherá aquele que está mais distante dos pontos de dados ou aquele que possui a margem máxima.</h4>

<center><img src="https://i.postimg.cc/9MR2fZSk/729834.webp"></center>

# **:: Vantagens do SVM**
---

<h4 align="justify">&bullet; <b>Funciona bem com dados complexos</b>:  o SVM é ótimo para conjuntos de dados em que a separação entre categorias não é clara. Ele pode lidar com dados lineares e não lineares de forma eficaz.</h4>
<h4 align="justify">&bullet; <b>Eficaz em espaços de alta dimensão</b>:  o SVM tem bom desempenho mesmo quando há mais recursos (dimensões) do que amostras, o que o torna útil para tarefas como classificação de texto ou reconhecimento de imagem. </h4>
<h4 align="justify">&bullet; <b>Evita overfitting</b>:  o SVM se concentra em encontrar o melhor limite de decisão (margem) entre classes, o que ajuda a reduzir o risco de overfitting, especialmente em dados de alta dimensão.</h4>
<h4 align="justify">&bullet; <b>Versátil com kernels</b>:  ao usar diferentes funções de kernel (como função de base linear, polinomial ou radial), o SVM pode se adaptar a vários tipos de dados e resolver problemas complexos.</h4>
<h4 align="justify">&bullet; <b>Robusto para outliers</b>:  o SVM é menos afetado por outliers porque se concentra nos vetores de suporte (pontos de dados mais próximos da margem), o que ajuda a criar um modelo mais generalizado.</h4>

# **:: Desvantagens do SVM**
---

<h4 align="justify">&bullet; <b>Lento com grandes conjuntos de dados</b>:  o SVM pode ser computacionalmente caro e lento para treinar, especialmente quando o conjunto de dados é muito grande.</h4>
<h4 align="justify">&bullet; <b>Difícil de ajustar</b>:  escolher o kernel e os parâmetros corretos (como C e gama) pode ser complicado e geralmente requer muita tentativa e erro.</h4>
<h4 align="justify">&bullet; <b>Não é adequado para dados ruidosos</b>:  se o conjunto de dados tiver muitas classes sobrepostas ou ruído, o SVM pode ter dificuldades para ter um bom desempenho porque tenta encontrar uma separação perfeita.</h4>
<h4 align="justify">&bullet; <b>Difícil de interpretar</b>:  Ao contrário de alguns outros algoritmos, os modelos SVM não são fáceis de interpretar ou explicar, especialmente quando se usam kernels não lineares.</h4>
<h4 align="justify">&bullet; <b>Consome muita memória</b>:  o SVM requer o armazenamento dos vetores de suporte, o que pode ocupar muita memória, tornando-o menos eficiente para conjuntos de dados muito grandes.</h4>

# **:: O que é o Kernel no SVM**
---

<h4 align="justify">O kernel é o truque que permite ao SVM resolver problemas em que os dados não podem ser separados por uma linha reta (ou plano em dimensões maiores). Ele transforma os dados em um espaço de dimensões superiores, onde uma separação linear se torna possível.</h4>

<center><img src="https://i.postimg.cc/vmWY7WX6/output-2.png"></center>

# **:: Tipos principais de Kernels**
---

<h4 align="justify">&bullet; <b>Linear</b>: usado quando os dados já podem ser separados com uma linha/hiperplano simples.</h4>
<h4 align="justify">&bullet; <b>Polinomial</b>: cria combinações de atributos (como x₁², x₂², x₁·x₂), transformando o espaço e permitindo separações mais complexas.
<h4 align="justify">&bullet; <b>Sigmóide</b>: funciona de forma parecida com neurônios artificiais, projetando os dados em valores entre 0 e 1.</h4>
<h4 align="justify">&bullet; <b>RBF (Radial Basis Function)</b>: o mais popular; cria combinações não lineares e projeta os dados em um espaço de dimensão muito alta, onde ficam mais separáveis.</h4>
<h4 align="justify">&bullet; <b>Bessel e ANOVA</b>: menos comuns, usados em casos específicos (funções matemáticas e regressões multidimensionais).</h4>

# **:: Como escolher o Kernel certo**
---

<h4 align="justify">&bullet; <b>Dados simples e separáveis</b>: comece com o Linear.</h4>
<h4 align="justify">&bullet; <b>Dados mais complexos</b>: geralmente o RBF é a melhor aposta.
<h4 align="justify">&bullet; <b>Polinomial e outros</b>: só em casos bem específicos, pois são mais custosos e menos eficientes.</h4>
<h4 align="justify">&bullet; <b>Regra prática</b>: se Linear e RBF dão resultados semelhantes, escolha o Linear (é mais simples e rápido).</h4>

# **:: Usando o SVM**
---

<h4 align="justify">Imaginemos juntos a seguinte situação: na Amazônia, em plena época de estiagem, a combinação de altas temperaturas, baixa umidade e vários dias sem chuva cria condições ideais para o surgimento de incêndios. Os gestores ambientais recebem diariamente um grande volume de informações — desde índices de vegetação (NDVI) até o número de focos de queimadas recentes — mas precisam de ferramentas inteligentes para transformar esses dados em ações concretas.</h4>
<h4 align="justify">O desafio é claro: <b>como prever, com base nos dados ambientais, se uma região está em alto risco de incêndio ou não?</b> Essa previsão é essencial para orientar onde enviar brigadas de combate, onde emitir alertas para comunidades ribeirinhas e até como planejar restrições temporárias de queimadas controladas. O grande obstáculo está em equilibrar precisão e agilidade: errar para menos pode significar incêndios descontrolados, e errar para mais pode gerar desperdício de recursos.</h4>
<h4 align="justify">A proposta para vocês é usar o <b>algoritmo SVM (Support Vector Machine)</b> para treinar um modelo capaz de classificar automaticamente o risco de incêndio em cada ponto monitorado. A ideia é que, a partir das variáveis do dataset (temperatura, umidade, dias sem chuva, vento, NDVI, focos de queimadas e distância de corpos d’água), o modelo aprenda padrões e consiga antecipar situações críticas, apoiando a tomada de decisão em tempo real.</h4>

### **Carrega Bibliotecas**

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler

### **Carrega o dataset no DataFrame**

In [ ]:
# carregar o dataset
df = pd.read_csv("/content/amazonia_svm_risco_incendio.csv")

df.sample(3)

,temp_c,umidade_rel,dias_sem_chuva,vento_kmh,ndvi,focos_7d,dist_agua_km,score_risco,risco_incendio
525,38.05,61.7,6,34.6,0.168,6,7.28,-0.414,1
244,26.59,48.1,29,36.3,0.604,2,12.79,-2.588,1
273,27.26,69.6,15,35.1,0.555,10,4.17,-3.529,0

###**Separa os dados em treino e teste (70%/30%)**

In [ ]:
# Definir variáveis independentes (features) e variável alvo (target)
X = df.drop(columns=["score_risco", "risco_incendio"])  # todas as variáveis preditoras
y = df["risco_incendio"]                               # variável alvo (0 ou 1)

# Separar em treino (70%) e teste (30%), mantendo a proporção das classes
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,        # 30% para teste
    random_state=42,      # garante reprodutibilidade
    stratify=y            # mantém a proporção de classes
)

# Conferir os formatos
print("Formato X_train:", X_train.shape)
print("Formato X_test:", X_test.shape)
print("Distribuição classes treino:\n", y_train.value_counts(normalize=True))
print("Distribuição classes teste:\n", y_test.value_counts(normalize=True))

Formato X_train: (420, 7)
Formato X_test: (180, 7)
Distribuição classes treino:
 risco_incendio
0    0.619048
1    0.380952
Name: proportion, dtype: float64
Distribuição classes teste:
 risco_incendio
0    0.622222
1    0.377778
Name: proportion, dtype: float64

###**Padroniza os dados usando StandardScaler**

In [ ]:
# Padronizar com StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Conferir a média e desvio padrão após padronização
means = X_train_scaled.mean(axis=0).round(2)
stds = X_train_scaled.std(axis=0).round(2)

print(means)
print(stds)

[-0. -0. -0.  0.  0.  0.  0.]
[1. 1. 1. 1. 1. 1. 1.]

###**Treina o modelo SVM com kernel RBF**

In [ ]:
#Treinar
# Definir e treinar o modelo SVM com kernel RBF
svm_rbf = SVC(kernel="rbf", C=1.0, gamma="scale", random_state=42)
svm_rbf.fit(X_train_scaled, y_train)

SVC(random_state=42)

###**Avalia o desempenho com acurácia, matriz de confusão e relatórios de classificação**

In [ ]:
# Fazer previsões
y_pred = svm_rbf.predict(X_test_scaled)

In [ ]:
# Avaliar desempenho
print("Acurácia no teste:", round(accuracy_score(y_test, y_pred), 3))
print("\nMatriz de Confusão:\n", confusion_matrix(y_test, y_pred))
print("\nRelatório de Classificação:\n", classification_report(y_test, y_pred))

Acurácia no teste: 0.9

Matriz de Confusão:
 [[105   7]
 [ 11  57]]

Relatório de Classificação:
               precision    recall  f1-score   support

           0       0.91      0.94      0.92       112
           1       0.89      0.84      0.86        68

    accuracy                           0.90       180
   macro avg       0.90      0.89      0.89       180
weighted avg       0.90      0.90      0.90       180

###**Predição de um novo valor**

In [ ]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Exemplo de nova instância ambiental (um ponto de dados)
# Ordem das variáveis: [temp_c, umidade_rel, dias_sem_chuva, vento_kmh, ndvi, focos_7d, dist_agua_km]
nova_instancia = np.array([[35.0, 28.0, 15, 18.0, 0.35, 12, 7.5]])

# Padronizar a nova instância com o mesmo scaler usado no treino
nova_instancia_scaled = scaler.transform(nova_instancia)

# Fazer a predição
predicao = svm_rbf.predict(nova_instancia_scaled)

# Mostrar resultado
if predicao[0] == 1:
    print("🔥 Predição: ALTO RISCO de incêndio")
else:
    print("✅ Predição: BAIXO/MODERADO RISCO de incêndio")

🔥 Predição: ALTO RISCO de incêndio

###**Busca os melhores hiperparâmetros**

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Pipeline: padronização + SVM
base = Pipeline([
    ('scaler', StandardScaler()),
    ('svm', SVC(probability=True, random_state=42))
])

# Espaço de busca (kernels mais usados para SVM de classificação)
param_grid = {
    'svm__kernel': ['linear', 'rbf'],
    'svm__C': [0.5, 1, 5, 10],
    'svm__gamma': ['scale', 'auto']  # relevante quando kernel='rbf' (será ignorado em 'linear')
    # opcional: 'svm__class_weight': [None, 'balanced']
}

# Validação estratificada
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Grid Search (refit no melhor por acurácia)
grid = GridSearchCV(
    estimator=base,
    param_grid=param_grid,
    cv=cv,
    scoring='accuracy',
    n_jobs=-1,
    refit=True
)

# Treinar busca
grid.fit(X_train, y_train)

# Melhor estimador e hiperparâmetros
model = grid.best_estimator_
print("Melhores hiperparâmetros:", grid.best_params_)
print("Acurácia (CV melhor):", round(grid.best_score_, 4))

# Avaliar no conjunto de teste
y_pred = model.predict(X_test)
print("\nAcurácia (teste):", round(accuracy_score(y_test, y_pred), 4))
print("\nMatriz de confusão:\n", confusion_matrix(y_test, y_pred))
print("\nRelatório de classificação:\n", classification_report(y_test, y_pred))

Melhores hiperparâmetros: {'svm__C': 10, 'svm__gamma': 'scale', 'svm__kernel': 'linear'}
Acurácia (CV melhor): 0.919

Acurácia (teste): 0.9167

Matriz de confusão:
 [[103   9]
 [  6  62]]

Relatório de classificação:
               precision    recall  f1-score   support

           0       0.94      0.92      0.93       112
           1       0.87      0.91      0.89        68

    accuracy                           0.92       180
   macro avg       0.91      0.92      0.91       180
weighted avg       0.92      0.92      0.92       180

<div align="center">
  <font size="6" color="#0000ff"><b>Fim do Encontro 18!</b></font>
</div>